#ifndef VTA_SUBPROCESS_BASE_GLOBAL_H
#define VTA_SUBPROCESS_BASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VTA_SUBPROCESS_BASE_LIBRARY)
#define VTA_SUBPROCESS_BASE_EXPORT Q_DECL_EXPORT    
#else
#define VTA_SUBPROCESS_BASE_EXPORT Q_DECL_IMPORT
#endif

#endif // VTA_SUBPROCESS_BASE_GLOBAL_H
